### PR TITLE
George's multi-winner test 3

### PR DESCRIPTION
**Pull request by tarheel**
This was a fun one! The issue that @gngilbert found arose from a subtle mistake I had made in the order of operations in the `recordCurrentRecipientAsWinner` method in `CastVoteRecord` (which I think only became relevant once I switched the rounding mode to DOWN). I hope that the inline comment that I added to the code there makes sense.

image

### CODE REVIEW

**Comment by gngilbert** [comment]
Thanks. Will the new version be on the GitHub in the morning?

**Comment by tarheel** [comment]
Depends on when Jon or Hylton has a chance to review my changes. But I can send you an updated JAR before then if you want to test it.

**Comment by tarheel** [comment]
Hmm, not sure why that test is failing for you. All the tests are passing for me. I'll double-check it, though.

And yeah, I'll rename the file.

**Comment by HEdingfield** [comment]
I assume they all passed when you checked again? Very strange...

**Comment by tarheel** [comment]
> I assume they all passed when you checked again? Very strange...

Yeah. I think you'll have to debug this on your end. Must be something environment-specific...?

**Comment by HEdingfield** [comment]
Figured out that the date was a day off in my local version of the config file... very strange that pulling the master down didn't overwrite that, but oh well, fixed now.

**Pull request merged**
