### PR TITLE
Fix for clearballot parsing: ignore quoted text in non-header rows

### PR DESCRIPTION
**Pull request by artoonie**
Fix for clearballot parsing: ignore quoted text in non-header

### CODE REVIEW

**Comment by artoonie** [comment]
@ryu-seg two requests:
1. Can you split out the regex string into a private static member so it can be reused instead of copy/pasted?
2. Can you bump the version number from RC2 to RC3?

**Comment by ryu-seg** [comment]
@artoonie done! let me know if that looks good.

**Comment by artoonie** [comment]
LGTM, thank you! @yezr shall we merge then create a Release for this?

**Comment by yezr** [comment]
Malachi is confirming locally everything works as expected and when that is done we'll rip a release

**Comment by nurse-the-code** [comment]
Hey, do you want me to replicate the error on https://github.com/BrightSpots/rcv/tree/develop or https://github.com/BrightSpots/rcv/tree/release/1.3.1-release-candidates?

And which do you want me to test the fix based off of?

**Comment by nurse-the-code** [comment]
Hey, this is my plan for testing this.

1. Replicate the bug observed in https://github.com/BrightSpots/rcv/issues/880 on [develop](https://github.com/BrightSpots/rcv/tree/develop)
2. Test the fix of the bug (i.e. https://github.com/BrightSpots/rcv/pull/881/commits/f27f8433f73bd108f05bfabf58a3961b026df551 and https://github.com/BrightSpots/rcv/pull/881/commits/a8dcb1a0f0612324efc1bb5fb621f0c9ccbdfddc) against [develop](https://github.com/BrightSpots/rcv/tree/develop)
3. Replicate the bug observed in https://github.com/BrightSpots/rcv/issues/880 on [1.3.1-release-candidates](https://github.com/BrightSpots/rcv/tree/release/1.3.1-release-candidates)
4. Test the fix of the bug (i.e. https://github.com/BrightSpots/rcv/pull/881/commits/f27f8433f73bd108f05bfabf58a3961b026df551 and https://github.com/BrightSpots/rcv/pull/881/commits/a8dcb1a0f0612324efc1bb5fb621f0c9ccbdfddc) against [1.3.1-release-candidates](https://github.com/BrightSpots/rcv/tree/release/1.3.1-release-candidates)

Let me know what you think.

**Comment by artoonie** [comment]
Good call re: testing. Perhaps it would be useful to create a test case and replicate that test across repos.

I don't think we need an entirely separate test here; perhaps we can modify an existing test and ensure that it fails without this fix, and passes with this fix.

If that sounds good, I can go ahead and make such a test case.

**Comment by yezr** [comment]
> Hey, this is my plan for testing this.
> 
> 1. [x]  Replicate the bug observed in [Ignore quoted commas when parsing non-header-row CSV values in ClearBallotCvrReader #880](https://github.com/BrightSpots/rcv/issues/880) on [develop](https://github.com/BrightSpots/rcv/tree/develop)
> 2. [ ]  Test the fix of the bug (i.e. [f27f843](https://github.com/BrightSpots/rcv/commit/f27f8433f73bd108f05bfabf58a3961b026df551) and [a8dcb1a](https://github.com/BrightSpots/rcv/commit/a8dcb1a0f0612324efc1bb5fb621f0c9ccbdfddc)) against [develop](https://github.com/BrightSpots/rcv/tree/develop)
> 3. [ ]  Replicate the bug observed in [Ignore quoted commas when parsing non-header-row CSV values in ClearBallotCvrReader #880](https://github.com/BrightSpots/rcv/issues/880) on [1.3.1-release-candidates](https://github.com/BrightSpots/rcv/tree/release/1.3.1-release-candidates)
> 4. [ ]  Test the fix of the bug (i.e. [f27f843](https://github.com/BrightSpots/rcv/commit/f27f8433f73bd108f05bfabf58a3961b026df551) and [a8dcb1a](https://github.com/BrightSpots/rcv/commit/a8dcb1a0f0612324efc1bb5fb621f0c9ccbdfddc)) against [1.3.1-release-candidates](https://github.com/BrightSpots/rcv/tree/release/1.3.1-release-candidates)

We just need the last two. 1.3.1-RC2 fixes haven't made it back to `develop` yet. Testing `develop` we would expect to see the parsing issue and it is a little superfluous. We just need to confirm that we can recreate the issue in the 1.3.1-RC2 version Ryu is using and that the new commits fix it there.

**Comment by nurse-the-code** [comment]
Getting a merge conflict when the two commits in this PR against [develop](https://github.com/BrightSpots/rcv/tree/develop).

**Comment by artoonie** [comment]
I suspect the merge conflict is just that `develop` has updated the version number too?

**Comment by nurse-the-code** [comment]
> I suspect the merge conflict is just that `develop` has updated the version number too?

Maybe, but I don't remember seeing that. It was more that the class had changed a lot.

It is not a blocker since we are just testing the fix against [release/1.3.1-release-candidates](https://github.com/BrightSpots/rcv/tree/release/1.3.1-release-candidates), but I wanted to make sure we knew for future reference that when we merge [release/1.3.1-release-candidates](https://github.com/BrightSpots/rcv/tree/release/1.3.1-release-candidates) back into [develop](https://github.com/BrightSpots/rcv/tree/develop) that there will be some merge conflicts to fix.

**Comment by nurse-the-code** [comment]
I tested it on linux (`aarch_64` architecture). The fix works. Code looks good.

LGTM

**Pull request merged**
