### PR TITLE
Random Seed is optional; mark it as such in the UI

### PR DESCRIPTION
**Pull request by artoonie**
Prefer single-issue PRs just in case we close the other one and forget to re-integrate this minor change

### CODE REVIEW

**Review by tarheel — APPROVED** [review]

**Comment by HEdingfield** [comment]
Per https://github.com/BrightSpots/rcv/pull/636#issuecomment-1474931006, this should be reverted. It automatically disables the text box when it's not required, and it enables the textbox whenever it is required (in which case the * is accurate because it's a required field).

**Comment by tarheel** [comment]
How hard would it be to make the * dynamic also? I don't like that the label indicates that this field is required when we actually have (I believe) zero real users who need to use it. Not a big deal, but right now we're sort of optimizing for an edge case at the expense of the normal UX.

(I haven't taken the time to look, but I believe there are other fields that would benefit from similar treatment.)

**Comment by HEdingfield** [comment]
I think it would be a pain with very little gain, TBH, but not impossible.

This field _is_ required though whenever they choose an option that enables it. It won't pass validation if they choose a random method but don't provide a seed.

**Comment by tarheel** [comment]
Filed #647 for this as a nice-to-have.

**Pull request merged**
