### PR TITLE
add support for a minimum vote threshold

### PR DESCRIPTION
**Pull request by tarheel**

### CODE REVIEW

**Comment by moldover** [comment]
Do you prefer to rebase when merging?  That's my preference.

**Comment by tarheel** [comment]
Can you clarify your question? Do you mean in reference to this particular PR, or generally? I'm fine letting you merge your PR and then I can rebase and sort out this one.

**Comment by moldover** [comment]
I just meant in general.

**Comment by tarheel** [comment]
What's the alternative to rebasing when merging in general? I thought you had to...?

**Comment by moldover** [comment]
This explains the difference pretty well: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

Git hub gives you both options when merging the PR.

**Comment by tarheel** [comment]
Ah, thanks. Yes, I'm definitely used to rebasing, not merging master into the feature branch.

**Comment by tarheel** [comment]
Why did you close the PR?

**Comment by tarheel** [comment]
The workflow I've been using on my other project:
- Person A sends out PR.
- Person B starts a review and leaves comments on PR, then accepts it or requests changes.
- Person A updates the PR by force-pushing to the remote feature branch, and the process repeats until Person B has accepted the PR.
- Person A rebases and resolves conflicts as necessary, then merges the PR and deletes the feature branch.

**Pull request merged**
