### PR TITLE
License updates

### PR DESCRIPTION
**Pull request by moldover**
This updates our license to MPL 2.0  #551 

License: https://github.com/BrightSpots/rcv/blob/license_updates_551/LICENSE.html

Added Contributors Guide:  https://github.com/BrightSpots/rcv/blob/license_updates_551/contributor_guide.md

### CODE REVIEW

**Comment by moldover** [comment]
@rrojas350 see my question here: #551 ... the copyright notice needs to be entirely replaced on every source file (and the template)

**Review by tarheel — APPROVED** [review]

**Comment by moldover** [comment]
@artoonie I realized there is something we should consider - I updated the license file in the test_data repo, that might conflict with how you are using rcvis.  are you ok with updating the rcvis license if needed?  check out more background in issue #551

**Comment by artoonie** [comment]
Thanks for the heads up!

RCVis doesn't use any of the test_data, actually - that was for a separate project. Some files in RCVis may have been generated by the tabulator, but not as part of test_data.

**Comment by moldover** [comment]
Ok cool, in that case we can leave test_data with the new license and we're gg.

**Pull request merged**
