### PR TITLE
Hotfix 1.3.1 merge into master

### PR DESCRIPTION
**Pull request by artoonie**

### CODE REVIEW

**Comment by artoonie** [comment]
Note: Do not merge this.

This is a hotfix to push a small fix on top of 1.3.1.

**Review by HEdingfield — COMMENTED** [review]
You would also need to increment the version number to 1.3.1 in this PR I think, but I'm confused as to why it's showing a diff when I already made these changes in #626?

**Comment by artoonie** [comment]
This now has `develop` merged in, which includes all changes from develop and not just the hotfix. Is that intentional @HEdingfield ?

**Comment by HEdingfield** [comment]
> This now has `develop` merged in, which includes all changes from develop and not just the hotfix. Is that intentional @HEdingfield ?

Wasn't intentional :( I used the GH UI to resolve conflicts when merging it into develop, and it apparently did this, which is pretty annoying. I guess we want to reset this back a step and attempt to merge into master? Hopefully that doesn't screw stuff up.

**Comment by artoonie** [comment]
Yeah, the branch is going to stay in sync, even if there are two PRs for the same branch. Yeah, I'm happy resetting back a step.

**Comment by artoonie** [comment]
Okay, reset done!

**Review by HEdingfield — CHANGES_REQUESTED** [review]
I'm not seeing the version number change here... did you go back one step too far?

**Comment by artoonie** [comment]
Ah, maybe -- I cherry-picked the commit already in develop to hopefully avoid merge conflicts in the future.

**Review by HEdingfield — APPROVED** [review]

**Pull request merged**
