### PR TITLE
RSA Validation: Cherry-Picked ont 1.3.2 release

### PR DESCRIPTION
**Pull request by artoonie**
Cherry-picking #755 onto the 1.3.2 release

### CODE REVIEW

**Comment by HEdingfield** [comment]
Will leave this to @tarheel to approve, since he approved #755 (also because I'm unsure of how to actually test that this is WAI on my end).

**Comment by HEdingfield** [comment]
Also seems like we'd want to merge #765 first...

**Comment by artoonie** [comment]
We can merge either first. If this one goes in first, I'll cherry-pick the relevant commits in #765 so there are no merge conflicts.

To check if this works:
1. Run the tests
2. Download the verity files with .sig.xml hashes (available on Slack) and create a config that loads them. Then hit "Auto-Load Candidates." If the signature is valid, it will work. Change one of the signatures or data files. It will then fail.

**Comment by HEdingfield** [comment]
> To check if this works:
> 
> 1. Run the tests
> 2. Download the verity files with .sig.xml hashes (available on Slack) and create a config that loads them. Then hit "Auto-Load Candidates." If the signature is valid, it will work. Change one of the signatures or data files. It will then fail.

Trying out 2... there is no auto-load candidates option. Wasn't this something we added in 1.4.0?

**Comment by yezr** [comment]
> Wasn't this something we added in 1.4.0?
yep! You should also be able to run a tabulation to verify that the signature verification works. It won't tabulate if it can't verify the signature. 

Here are some of the illustrious candidates from that test data that you can put in manually
- Mickey Mouse
- Bugs Bunny
- Homer Simpson
- Woody Woodpecker
- Scrooge McDuck
- Toucan Sam

**Review by tarheel — APPROVED** [review]

**Comment by artoonie** [comment]
> Here are some of the illustrious candidates from that test data that you can put in manually

Yeah, sorry, this was the testing process before the cherry-pick.

**Comment by HEdingfield** [comment]
Tested this out locally with some of the candidates and it failed with "no cast vote records found". Tried it again after modifying one of the sig files and it failed with "Failure while trying to verify hash", so I guess that worked?  Ah well, merged now anyway!

**Pull request merged**
